### PR TITLE
builtin: Implement builtin function any, all.

### PR DESCRIPTION
**Pull request by corona10**
Hi, I have highly interested in this project.
I've experienced to work on the grumpy project also.

Anyway, this might be my first PR, Please take a look.

### CODE REVIEW

**Comment by corona10** [comment]
It looks like there is CI process on this project.
I hope this will be added.

**Comment by corona10** [comment]
@ncw Yeah great! Let s implement most of feature of Python 3.4 until late 2018 :)

**Comment by sbinet** [comment]
Would you be willing to migrate this project to the go-python organization?
We don't have much more peoplepower, but we could have a bit of turnover...

**Comment by ncw** [comment]
@sbinet can you drop me an email to nick@craig-wood.com and we can discuss - thanks!

**Pull request merged**
